android: kernel_version: fix for pre-M and align to AOSP Settings.
On Android versions previous to M (Marshmallow), `uname` command is not
available, leading to an exception while computing `kernel_version` :

 E/com.getsentry.raven.android.event.helper.AndroidEventBuilderHelper: Exception while attempting to read kernel information
   java.io.IOException: Error running exec(). Command: [uname, -a] Working Directory: null Environment: null
       at java.lang.ProcessManager.exec(ProcessManager.java:211)
       at java.lang.Runtime.exec(Runtime.java:173)
       at java.lang.Runtime.exec(Runtime.java:246)
       at java.lang.Runtime.exec(Runtime.java:189)
       at com.getsentry.raven.android.event.helper.AndroidEventBuilderHelper.getKernelVersion(AndroidEventBuilderHelper.java:267)
       at com.getsentry.raven.android.event.helper.AndroidEventBuilderHelper.<clinit>(AndroidEventBuilderHelper.java:41)
       at com.getsentry.raven.android.AndroidRavenFactory.createRavenInstance(AndroidRavenFactory.java:44)
       at com.getsentry.raven.RavenFactory.ravenInstance(RavenFactory.java:103)
       at com.getsentry.raven.RavenFactory.ravenInstance(RavenFactory.java:73)
       at com.getsentry.raven.android.Raven.init(Raven.java:140)
       at com.getsentry.raven.android.Raven.init(Raven.java:90)
       at com.getsentry.raven.android.Raven.init(Raven.java:69)
       at com.getsentry.raven.android.Raven.init(Raven.java:41)

The proposed solution is to use the kernel version string used by AOSP
in Settings application as it relies on `/proc/version` file which is
world readable.

This will change the format of `kernel_version`.